accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'sign_in/$', views.sign_in, name='sign_in'),
    url(r'sign_up/$', views.sign_up, name='sign_up'),
    url(r'sign_out/$', views.sign_out, name='sign_out'),
    url(r'profile/$', views.view_profile, name='view_profile'),
    url(r'profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^change_password/$', views.change_password, name='change_password'),
]

project_7/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from . import views

# app_name = 'project_7'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^$', views.home, name='home'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from ckeditor.fields import RichTextField


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField()
    verify_email = models.EmailField()
    birth_date = models.DateField(null=True, blank=True)
    bio = RichTextField(max_length=500, blank=True)
    avatar = models.ImageField(upload_to='avatars', null=True, blank=True,
                               default='default-user-profile.png')
    city = models.CharField(max_length=30, blank=True)
    state = models.CharField(max_length=30, blank=True)
    country_of_residence = models.CharField(max_length=30, blank=True)
    favorite_animal = models.CharField(max_length=30, blank=True)
    hobby = models.CharField(max_length=30, blank=True)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

accounts/forms.py
from PIL import Image
from django import forms
from django.core import validators
from . import models
from ckeditor.widgets import CKEditorWidget
from .widgets import FengyuanChenDatePickerInput


class UserForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = [
            'first_name',
            'last_name',
        ]


class ProfileForm(forms.ModelForm):
    bio = forms.CharField(widget=CKEditorWidget(),
                          validators=[validators.MinLengthValidator(10)]
                          )
    birth_date = forms.DateField(
        input_formats=['%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y'],
        widget=FengyuanChenDatePickerInput()
    )
    avatar = forms.ImageField(widget=forms.FileInput, required=False)

    # Avatar parameters will be hidden,
    # need them for FE to BE calculations
    x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height = forms.FloatField(widget=forms.HiddenInput(), required=False)
    rotate = forms.IntegerField(widget=forms.HiddenInput(), required=False)
    scaleX = forms.IntegerField(widget=forms.HiddenInput(), required=False)
    scaleY = forms.IntegerField(widget=forms.HiddenInput(), required=False)

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get("email")
        verify_email = cleaned_data.get('verify_email')

        if email != verify_email:
            raise forms.ValidationError(
                    "You need to enter the same email in both fields"
                )

    class Meta:
        model = models.Profile
        fields = [
            'email',
            'verify_email',
            'birth_date',
            'bio',
            'avatar',
            'city',
            'state',
            'country_of_residence',
            'favorite_animal',
            'hobby',
        ]

    def save(self):
        profile = super().save()

        # save avatar picture if only a new one has been selected
        if len(self.files):
            x = self.cleaned_data.get('x')
            y = self.cleaned_data.get('y')
            w = self.cleaned_data.get('width')
            h = self.cleaned_data.get('height')
            rotate = self.cleaned_data.get('rotate')
            scaleX = self.cleaned_data.get('scaleX')
            scaleY = self.cleaned_data.get('scaleY')

            image = Image.open(profile.avatar)

            if scaleX == -1:
                image = image.transpose(Image.FLIP_LEFT_RIGHT)
            if scaleY == -1:
                image = image.transpose(Image.FLIP_TOP_BOTTOM)
            if rotate:
                image = image.rotate(rotate*-1, expand=True)

            if x or y or w or h:
                image = image.crop((x, y, w + x, h + y))

            image.save(profile.avatar.path)

        return profile

accounts/views.py
from django.contrib import messages
from django.contrib.auth import (authenticate, login, logout,
                                 update_session_auth_hash)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import (AuthenticationForm, UserCreationForm,
                                       PasswordChangeForm)
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

from . import forms


def sign_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            if form.user_cache is not None:
                user = form.user_cache
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(
                        reverse('home')
                    )
                else:
                    messages.error(
                        request,
                        "That user account has been disabled."
                    )
            else:
                messages.error(
                    request,
                    "Username or password is incorrect."
                )
    return render(request, 'accounts/sign_in.html', {'form': form})


def sign_up(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1']
            )
            login(request, user)
            messages.success(
                request,
                "You're now a user! You've been signed in, too."
            )
            return HttpResponseRedirect(reverse('accounts:edit_profile'))
    return render(request, 'accounts/sign_up.html', {'form': form})


def sign_out(request):
    logout(request)
    messages.success(request, "You've been signed out. Come back soon!")
    return HttpResponseRedirect(reverse('home'))


@login_required
def edit_profile(request):
    if request.method == 'POST':
        user_form = forms.UserForm(request.POST, request.FILES,
                                   instance=request.user)
        profile_form = forms.ProfileForm(request.POST, request.FILES,
                                         instance=request.user.profile)

        # Don't bother to save unless user or profile forms were changed
        if user_form.is_valid() and profile_form.is_valid():
            if user_form.has_changed():
                user_form.save()
            if profile_form.has_changed():
                profile_form.save()
            if user_form.has_changed() or profile_form.has_changed():
                messages.success(request,
                                 'Your profile was successfully updated!')
            return HttpResponseRedirect(reverse('accounts:view_profile'))
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        user_form = forms.UserForm(instance=request.user)
        profile_form = forms.ProfileForm(instance=request.user.profile)
    return render(request, 'accounts/edit_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })


@login_required
def view_profile(request):
    user_form = forms.UserForm()
    profile_form = forms.ProfileForm()
    if request.method == 'GET':
        user_form = forms.UserForm(data=None,
                                   instance=request.user)
        profile_form = forms.ProfileForm(data=None,
                                         instance=request.user.profile)

    return render(request, 'accounts/view_profile.html',
                  {
                      'user_form': user_form,
                      'profile_form': profile_form,
                   })


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # keeps the user logged in
            messages.success(request, 'Your password was successfully updated!')
            return redirect('accounts:view_profile')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/change_password.html', {
        'form': form
    })

accounts/templates/accounts/change_password.html
{% extends "layout.html" %}

{% block title %}Change Password | {{ super }}{% endblock %}

{% block body %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="Save changes">
</form>
{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends "layout.html" %}

{% block title %}Profile | {{ super }}{% endblock %}
{% block js_fc_datepicker %}
  <!-- Fengyuan Chen's Datepicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
{% endblock js_fc_datepicker %}

{% block body %}
<form method="POST" action="{% url 'accounts:edit_profile' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.media }}
    {{ user_form.as_p }}
    {{ profile_form.media }}
    {{ profile_form.as_p }}
    <input type="submit" class="button-primary" value="Save Profile">

</form>

<!--=====================================
 FORM MODAL
=====================================-->
<div class="modal fade text-dark" id="register" tabindex="-1" role="dialog" aria-labelledby="register form" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header" style="background-color:#537d7b">
        <h5 class="modal-title" id="exampleModalLabel" style="color: white">Edit Your Avatar</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <!-- Registeration Form -->
          <div class="profile-img">
            <img id="image" class= "img-fluid rounded d-none d-sm-block" src="" alt="editing profile picture..."/>
          </div>
          <hr class="my-4">
          <div class="row">
            <div class="col-sm-2">
              <button type="button" class="button-primary js-crop-toggler fas fa-crop fa-lg" data-toggle="button" aria-pressed="true" autocomplete="off"></button>
            </div>
            <div class="col-sm-2">
              <button type="button" class="button-primary js-flip-V-toggler fas fa-arrows-alt-v fa-lg" data-toggle="button" aria-pressed="false" autocomplete="off"></button>
            </div>
            <div class="col-sm-2">
              <button type="button" class="button-primary js-flip-h-toggler fas fa-arrows-alt-h fa-lg" data-toggle="button" aria-pressed="false" autocomplete="off"></button>
            </div>
            <div class="col-sm-2">
              <button type="button" class="button-primary js-rotate-left fas fa-undo fa-lg"></button>
            </div>
            <div class="col-sm-2">
              <button type="button" class="button-primary js-rotate-right fas fa-redo fa-lg"></button>
            </div>
          </div>
          <hr class="my-4">
          <div class="row">
            <div class="col-sm-4">
              <button type="button" class="button-primary js-save-settings text-sm">Save Settings</button>
            </div>
            <div class="col-sm-2">
              <button type="button" class="button-secondary text-sm" data-dismiss="modal">Cancel</button>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}
{% block javascript %}
  <script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $('#id_avatar').on('click touchstart' , function(){
        $(this).val('');
      });

      $("#id_avatar").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#register").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      $("#register").on("shown.bs.modal", function () {
        $(image).cropper({
          checkOrientation: false,
          zoomable: false,
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 100,
          minCropBoxHeight: 100,
          ready: function () {
            // we can run methods in here
          }
        });
      }).on("hidden.bs.modal", function () {
        // we can run methods in here
        $image.cropper("destroy");
      });
      $(".js-rotate-left").click(function () {
        $image.cropper("rotate", -90);
      });

      $(".js-rotate-right").click(function () {
        $image.cropper("rotate", 90);
      });

      //Crop Toggler
      function crop_off() {
        $image.cropper("clear");
        $(this).one("click", crop_on);
      }
      function crop_on() {
        $image.cropper("crop");
        $(this).one("click", crop_off);
      }
      $(".js-crop-toggler").one("click", crop_off);

      //Flip-H Toggler
      function flip_h_off() {
        $image.cropper("scaleX", 1);
        $(this).one("click", flip_h_on);
      }
      function flip_h_on() {
        $image.cropper("scaleX", -1);
        $(this).one("click", flip_h_off);
      }
      $(".js-flip-h-toggler").one("click", flip_h_on);

      //Flip-V Toggler
      function flip_v_off() {
        $image.cropper("scaleY", 1);
        $(this).one("click", flip_v_on);
      }
      function flip_v_on() {
        $image.cropper("scaleY", -1);
        $(this).one("click", flip_v_off);
      }
      $(".js-flip-V-toggler").one("click", flip_v_on);

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-save-settings").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#id_rotate").val(cropData["rotate"]);
        $("#id_scaleX").val(cropData["scaleX"]);
        $("#id_scaleY").val(cropData["scaleY"]);
        $('#register').modal('hide')
      });

    });
  </script>

{% endblock %}

accounts/templates/accounts/sign_in.html
{% extends "layout.html" %}

{% block title %}Sign In | {{ super }}{% endblock %}

{% block body %}
<form method="POST" action="{% url 'accounts:sign_in' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="Sign In">
</form>
{% endblock %}

accounts/templates/accounts/sign_up.html
{% extends "layout.html" %}

{% block title %}Sign Up | {{ super }}{% endblock %}

{% block body %}
<form method="POST" action="{% url 'accounts:sign_up' %}">
    {% csrf_token %}

    {{ form.non_field_errors }}

    {% for hidden_field in form.hidden_fields %}
        {{ hidden_field.errors }}
        {{ hidden_field }}
    {% endfor %}

    {% for field in form.visible_fields %}
        <p>
        {{ field.label_tag }}
        {{ field.errors }}
        {{ field }}
        {% if field.help_text %}
            <span class="helptext">{{ field.help_text }}</span>
        {% endif %}
      </p>
    {% endfor %}
    <input type="submit" class="button-primary" value="Sign Up">
</form>
{% endblock %}

accounts/templates/accounts/view_profile.html
{% extends "layout.html" %}

{% block title %}Profile | {{ super }}{% endblock %}

{% block body %}

    <div class="row">
        <div class="col-md-12">
            <h3>Your Profile</h3>
            <hr>
        </div>
    </div>
    <div class="container mt-3 row">
        <div class="col-md-4 pb-4">
            <div class="profile-img">
                <img class= "img-fluid rounded d-none d-sm-block" src="{{ profile_form.instance.avatar.url }}" alt="..."/>
            </div>
        </div>
        <div class="col-md-8">
        {% for field in user_form.visible_fields %}
            <div>
                <dl class="row">
                  <dt class="col-sm-4 h4 font-weight-normal">{{ field.label_tag }}</dt>
                  <dd class="col-sm-8 h3 font-weight-normal text-secondary">{{ field.value }}</dd>
                </dl>
            </div>
        {% endfor %}
        {% for field in profile_form.visible_fields %}
            {% if field.name != "avatar" and field.name != "verify_email" %}
            <div>
                <dl class="row">
                  <dt class="col-sm-4 h4 font-weight-normal">{{ field.label_tag }}</dt>
                  <dd class="col-sm-8 h3 font-weight-normal text-secondary">{{ field.value | safe }}</dd>
                </dl>
            </div>
            {% endif %}
        {% endfor %}
        </div>
    </div>
{% endblock %}