accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'sign_in/$', views.sign_in, name='sign_in'),
    url(r'sign_up/$', views.sign_up, name='sign_up'),
    url(r'sign_out/$', views.sign_out, name='sign_out'),
    url(r'profile/$', views.view_profile, name='view_profile'),
    url(r'profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^change_password/$', views.change_password, name='change_password'),
]

project_7/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from . import views

# app_name = 'project_7'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^$', views.home, name='home'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/home.html
{% extends 'layout.html' %}
{% block body %}
    <div class="grid-25">

    </div>
    <div class="grid-75">
        <h2 class="display-2">Welcome To Profile System!</h2>
        <p class="lead">Make your self a profile. It's easy and beautiful.</p>
        <div class="pl-4">
        <ul><span class="display-4">We Have:</span>
          <li>Rich Formatted-Text for Biography</li>
          <li>Date Pickers widgets for date fields</li>
          <li>Avatar Editor</li>
          <li>Change Password Option</li>
          <li>Password Strength Meter</li>
        </ul>
        </div>
        <hr m-2>
        <p>We have cheerfully built this system to ease your organization members profile, Please Feel free to contact for any new feature requests or help.</p>
    </div>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Basic Page Needs
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta charset="utf-8">
    <title>{% block title %}Circle{% endblock %}</title>

    <!-- Mobile Specific Metas
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- FONTS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine'
          rel='stylesheet' type='text/css'>

    <!-- CSS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/global.css" %}">
    <link rel="stylesheet" href="{% static "css/password.min.css" %}">
    <link rel="stylesheet" href="{% static "css/cropper.min.css" %}">
    <script src="https://kit.fontawesome.com/d42aef1197.js"></script>
    <style>
        .dropdown-item:focus, .dropdown-item:hover {
            color: #16181b;
            text-decoration: none;
            background-color: rgba(148, 209, 207, 0.41);
        }
        .dropdown-menu {
            background-color: #537d7b;
            font-size: 80%;
        }
    </style>

    <!-- JS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <!-- jQuery -->
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static "js/autogrow.js" %}"></script>
    <script type="text/javascript" src="{% static "js/password.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/cropper.min.js" %}"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block js_fc_datepicker %}{% endblock js_fc_datepicker %}
    <script type="text/javascript" src="{% static "js/global.js" %}"></script>
</head>
<body>
<header class="circle--header">
    <div class="bounds">
        <div class="circle--fluid">
            <div class="circle--fluid--cell">
                <h1 class="hide-text circle--logo"><a class="logo"
                                                      href="{% url 'home' %}">Circle</a>
                </h1>
            </div>
            <div class="circle--fluid--cell circle--fluid--primary">
                <nav>
                    <ul class="circle--inline">
                        {% if user.is_authenticated %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                  Account
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown"> <!-- style="background-color: #537d7b" -->
                                  <a class="dropdown-item" href="{% url 'accounts:edit_profile' %}">Edit Profile</a>
                                  <a class="dropdown-item" href="{% url 'accounts:change_password' %}">Change Password</a>
                                </div>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
            <div class="circle--fluid--cell circle--fluid--secondary">
                <nav>
                    <ul class="circle--inline">
                        {% if not user.is_authenticated %}
                            <li><a href="{% url 'accounts:sign_up' %}">Sign Up</a></li>
                            <li><a href="{% url 'accounts:sign_in' %}">Sign
                                In</a></li>
                        {% else %}
                            <li><a href="{% url 'accounts:view_profile' %}">View Profile</a></li>
                            <li><a href="{% url 'accounts:sign_out' %}">Sign Out</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>

<div class="bounds circle--page">
    {% if messages %}
        <ul class="messages centered grid-50">
            {% for message in messages %}
                <li{% if message.tags %}
                    class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <div class="container">
        {% block body %}{% endblock %}
    </div>
</div>
{% block javascript %}{% endblock %}
</body>
</html>